spring:
  application:
    name: WillBeeDone

  datasource:
    url: jdbc:mysql://${LDB_HOST}:${LDB_PORT}/${LDB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LDB_USERNAME}
    password: ${LDB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    enabled: false

  mail:
    username: ${MAIL_FROM}
    password: ${MAIL_FROM_PASSWORD}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com

key:
  access: ${ACCESS_PHRASE_SECRET} # для JWT доступа
  refresh: ${REFRESH_PHRASE_SECRET} # для JWT refresh
  google-client-id: ${GOOGLE_CLIENT_ID} # сюда добавь свой Google Client ID
  google-client-secret: ${GOOGLE_CLIENT_SECRET} # сюда свой Google Client Secret

server:
  servlet:
    context-path: /api

base:
  url: ${BASE_URL}

# Конфигурация для Google OAuth
google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI} # для получения ответа от Google OAuth
