spring:
  application:
    name: WillBeeDone

  datasource:
    url: jdbc:mysql://${LDB_HOST}:${LDB_PORT}/${LDB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LDB_USERNAME}
    password: ${LDB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    enabled: false

  mail:
    username: ${MAIL_FROM}
    password: ${MAIL_FROM_PASSWORD}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

logging:
  file:
    name: logs/log.log
  level:
    root: info
    de.willbeedone.backend: info
    org.springframework.aop: DEBUG
    org.aspectj: DEBUG

key:
  access: ${ACCESS_PHRASE_SECRET}
  refresh: ${REFRESH_PHRASE_SECRET}

server:
  servlet:
    context-path: /api

base:
  url: ${BASE_URL}

messages:
  hello: Hello from local application!