spring:
  application:
    name: WillBeeDone

  datasource:
    url: ${LDB_DATABASE}//${LDB_HOST}:${LDB_PORT}/${LDB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LDB_USERNAME}
    password: ${LDB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
