spring:
  application:
    name: WillBeeDone

  datasource:
    url: ${LDB_DATABASE}//${LDB_HOST}:${LDB_PORT}/${LDB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LDB_USERNAME}
    password: ${LDB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    enabled: false

server:
  servlet:
    context-path: /api