<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Password Reset</title>
</head>
<body>
<h1 style="color: green">Password reset</h1>
<h2>Hello, ${name}!</h2>
<p>You received this message because there was a request to change your password.</p>
<p>If you did not make this request then please ignore this email.</p>
<p>Otherwise, please follow this <a href="${link}">link</a> to change your password.</p>
</body>
</html>